In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class perceptron():
    def __init__(self,input_size:int):
        self.input_size = input_size
        self.biases = np.random.randn(1,1)
        self.weights = np.random.randn(1,self.input_size) 
        """initial weights and biases"""
        
    def heavy_side(self,z):
        """activation function for perceptron"""
        if z<0:
            return 0
        else:
            return 1.
    
    def feedforward(self,a):
      
        return self.heavy_side(np.dot(self.weights,a)+self.biases)
    
    def update(self, learning_rate,x,y):

        self.weights=self.weights+learning_rate*(y-self.feedforward(x))*x.T
        self.biases=self.biases+learning_rate*(y-self.feedforward(x))
        
    
    def learn(self,data,target,learning_rate):
        counter=0 
        while True:
            old_w=self.weights
            old_b=self.biases
            for x,y in zip(data,target):
                x.reshape(self.input_size,1)
                y.reshape(1,1)
                self.update(learning_rate,x,y)
                print([self.feedforward(x) for x in data])
                
            counter+=1
            if np.all(old_w==self.weights) and old_b==self.biases: #update가 되지 않을때 까지
                print(counter)
                break

# OR 
* 단층 perceptron을 이용하여 다음의 데이터를 분류하여라.

In [3]:
X =np.array([[0,0],[1,0],[0,1],[1,1]])
y =np.array([0,1,1,1])
print(np.shape(X))
print(np.shape(y))
print(y)

(4, 2)
(4,)
[0 1 1 1]


In [4]:
single_perceptron=perceptron(2)
single_perceptron.learn(X,y,0.1)

[1.0, 0, 0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[0, 0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
[0, 1.0, 1.0, 1.0]
12


In [5]:
print(single_perceptron.weights)
print(single_perceptron.biases)
print(np.array([single_perceptron.feedforward(np.array(x).reshape(2,1)) for x in X])==y)

[[0.02551163 0.21954098]]
[[-0.02050634]]
[ True  True  True  True]


# Iris classifications

* 단층 perceptron을 이용하여 다음의 데이터를 분류하여라.

In [6]:
from sklearn import datasets
iris = datasets.load_iris() # 분꽃
print(iris.target_names) # 3종류의 분꽃 분류하기
print(iris.feature_names) # features


['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
Xi=iris.data # input data # the number of input nodes = 4
print(len(Xi))

150


In [8]:
iris.target_names # setosa = 0, not setosa = 1

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
yi=np.where(iris.target>0,1,0) # 0(setosa) 과 1(setosa 외) 로 분류
print(len(y))

4


* 위의 데이터를 단층 perceptron을 이용하여 분류하는 신경망을 만들고 학습하여라.
* 입력층의 노드는 바이어스를 제외하고 4개로 한다. 바이어스 1개를 포함 총 5개이다. 
* 출력층의 노드는 1개로 한다.

In [10]:
iris_perceptron=perceptron(4)

In [11]:

iris_perceptron.learn(Xi,yi,0.01)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0

In [12]:
print(np.array([iris_perceptron.feedforward(np.array(x).reshape(4,1)) for x in Xi])==yi)
print(iris_perceptron.weights)
print(iris_perceptron.biases)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[[ 0.32980325 -0.98042515  0.76952629 -0.04203272]]
[[-1.18260424]]
